/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0959f38cbbfd54627b12395665c587aa)
interface __BaseEnv_Env {
	AUTH_SECRET: string;
	HEYIWEI_G2_KEY: string;
	HEYIWEI_G9_KEY: string;
	HEYIWEI_G13_KEY: string;
	HEYIWEI_G35_KEY: string;
	HEYIWEI_G39_KEY: string;
	HEYIWEI_G42_KEY: string;
	HAIBAO_G2_KEY: string;
	HAIBAO_G19_KEY: string;
	DEEPSEEK_API_KEY: string;
	HEYIWEI_CONSOLE_REFRESH_TOKEN: string;
	AssistantDirectory: DurableObjectNamespace<import("./src/server").AssistantDirectory>;
	ProviderStatus: DurableObjectNamespace<import("./src/server").ProviderStatus>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "AssistantDirectory" | "ProviderStatus";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SECRET" | "HEYIWEI_G2_KEY" | "HEYIWEI_G9_KEY" | "HEYIWEI_G13_KEY" | "HEYIWEI_G35_KEY" | "HEYIWEI_G39_KEY" | "HEYIWEI_G42_KEY" | "HAIBAO_G2_KEY" | "HAIBAO_G19_KEY" | "DEEPSEEK_API_KEY" | "HEYIWEI_CONSOLE_REFRESH_TOKEN">> {}
}
